/**
 * Offline-capable Prisma migration runner.
 *
 * `prisma migrate` normally downloads a native schema-engine binary from
 * binaries.prisma.sh. In restricted networks (CI sandboxes, air-gapped build
 * agents) that download fails, so this script drives the exact same engine via
 * the WebAssembly build that ships on npm (`@prisma/schema-engine-wasm`).
 *
 * The migration files it writes are plain Prisma migrations: environments with
 * unrestricted network access can keep using `prisma migrate dev/deploy`.
 *
 * Usage:
 *   tsx scripts/migrate.ts create <name>   # generate a new migration folder
 *   tsx scripts/migrate.ts deploy          # apply pending migrations
 *   tsx scripts/migrate.ts reset           # drop everything, re-apply
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { PrismaPg } from '@prisma/adapter-pg';
import { bindMigrationAwareSqlAdapterFactory } from '@prisma/driver-adapter-utils';
import { SchemaEngine } from '@prisma/schema-engine-wasm';
import type { MigrationList, SchemaFilter } from '@prisma/schema-engine-wasm';

const ROOT = process.cwd();
const SCHEMA_PATH = path.join(ROOT, 'prisma', 'schema.prisma');
const MIGRATIONS_DIR = path.join(ROOT, 'prisma', 'migrations');
const LOCKFILE = 'migration_lock.toml';
const FILTERS: SchemaFilter = { externalTables: [], externalEnums: [] };

function connectionString(): string {
  const url = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
  if (!url) {
    throw new Error('DATABASE_URL (or DIRECT_URL) must be set to run migrations.');
  }
  return url;
}

function readSchema(): string {
  return readFileSync(SCHEMA_PATH, 'utf8');
}

function readMigrationsList(): MigrationList {
  mkdirSync(MIGRATIONS_DIR, { recursive: true });
  const lockPath = path.join(MIGRATIONS_DIR, LOCKFILE);

  const migrationDirectories = readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((name) => ({
      path: name,
      migrationFile: {
        path: 'migration.sql',
        content: {
          tag: 'ok' as const,
          value: readFileSync(path.join(MIGRATIONS_DIR, name, 'migration.sql'), 'utf8'),
        },
      },
    }));

  return {
    baseDir: MIGRATIONS_DIR,
    lockfile: {
      path: LOCKFILE,
      content: existsSync(lockPath) ? readFileSync(lockPath, 'utf8') : null,
    },
    shadowDbInitScript: '',
    migrationDirectories,
  };
}

async function withEngine<T>(fn: (engine: SchemaEngine) => Promise<T>): Promise<T> {
  const schema = readSchema();
  const factory = bindMigrationAwareSqlAdapterFactory(
    new PrismaPg({ connectionString: connectionString() }),
  );
  const engine = await SchemaEngine.new(
    { datamodels: [['schema.prisma', schema]] },
    () => {},
    factory,
  );
  try {
    return await fn(engine);
  } finally {
    engine.free();
  }
}

async function create(name: string): Promise<void> {
  const schema = readSchema();
  const migrationsList = readMigrationsList();

  // Diff the committed migration history against the current datamodel. This
  // mirrors what `prisma migrate dev` produces, without a native engine.
  const result = await withEngine((engine) =>
    engine.diff({
      from:
        migrationsList.migrationDirectories.length === 0
          ? { tag: 'empty' }
          : { tag: 'migrations', ...migrationsList },
      to: { tag: 'schemaDatamodel', files: [{ path: 'schema.prisma', content: schema }] },
      script: true,
      exitCode: null,
      filters: FILTERS,
    }),
  );

  const script = result.stdout?.trim();
  if (!script) {
    console.log('No schema changes detected — nothing to migrate.');
    return;
  }

  const timestamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
  const directoryName = `${timestamp}_${name.replace(/[^a-zA-Z0-9]+/g, '_').toLowerCase()}`;
  const dir = path.join(MIGRATIONS_DIR, directoryName);
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, 'migration.sql'), `${script}\n`, 'utf8');
  writeFileSync(
    path.join(MIGRATIONS_DIR, LOCKFILE),
    '# Please do not edit this file manually\n# It should be added in your version-control system (e.g. Git)\nprovider = "postgresql"\n',
    'utf8',
  );
  console.log(`Created migration ${directoryName}`);
}

async function deploy(): Promise<void> {
  const output = await withEngine((engine) =>
    engine.applyMigrations({ migrationsList: readMigrationsList(), filters: FILTERS }),
  );
  if (output.appliedMigrationNames.length === 0) {
    console.log('No pending migrations.');
    return;
  }
  for (const name of output.appliedMigrationNames) {
    console.log(`Applied ${name}`);
  }
}

async function reset(): Promise<void> {
  await withEngine((engine) => engine.reset({ filter: FILTERS }));
  console.log('Database reset.');
  await deploy();
}

async function main(): Promise<void> {
  const [command, ...args] = process.argv.slice(2);

  switch (command) {
    case 'create': {
      const name = args[0];
      if (!name) throw new Error('Usage: tsx scripts/migrate.ts create <name>');
      await create(name);
      break;
    }
    case 'deploy':
      await deploy();
      break;
    case 'reset':
      await reset();
      break;
    default:
      throw new Error(`Unknown command "${command ?? ''}". Use create | deploy | reset.`);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
